[package]
name = "ray"
version = "0.1.0"
authors = ["3541 <alex@emobrien.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
derive_more = "*"
rand = "*"
once_cell = "*"

[profile.release]
lto = true
codegen-units = 1
